name: redis-inactivity-monitor

services:
  redis:
    container_name: redis-inactivity-monitor
    image: redis:8.2-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-inactivity-monitor-data:/data
    networks:
      - redis-inactivity-monitor-network
    restart: unless-stopped

volumes:
  redis-inactivity-monitor-data:
    name: redis-inactivity-monitor-data

networks:
  redis-inactivity-monitor-network:
    driver: bridge
